name: Data Quality Pipeline

on:
  push:
  pull_request:

jobs:
  data-quality-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          mkdir -p reports
          pytest -v --maxfail=1 --disable-warnings --junitxml=reports/pytest-report.xml

      - name: Generate Data Metrics
        run: pytest -q --disable-warnings -k "data_quality_metrics"

      - name: Publish Data Metrics Summary
        run: |
          echo "## Data Metrics" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          python - << 'EOF'
          import json, pathlib, os
    
          metrics_file = pathlib.Path("reports/data_metrics.json")
          if metrics_file.exists():
            metrics = json.loads(metrics_file.read_text())
            
            lines = []
            lines.append("| Metric | Value |")
            lines.append("|--------|-------|")
            
            for k, v in metrics.items():
              lines.append(f"| {k} | {v} |")
              
            lines.append("")
            
            with open(os.environ["GITHUB_STEP_SUMMARY"], "a") as summary:
              summary.write("\n".join(lines))
          else:
            print("No data_metrics.json found")
          EOF

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: dq-reports
          path: |
            reports/
            **/data_metrics.json
